# Generated by Django 3.2.13 on 2022-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='test', max_length=100, verbose_name='Title of Group'),
            preserve_default=False,
        ),
    ]
