# Generated by Django 3.2.13 on 2022-09-04 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('hotplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupblacklist',
            name='blocked_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_blocked_group', to='group.group'),
        ),
        migrations.AddField(
            model_name='groupblacklist',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_group', to='group.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='hotplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotplace.hotplace'),
        ),
    ]
