# Generated by Django 3.2.13 on 2022-06-24 16:36

from django.db import migrations, models
import django.db.models.deletion
import heythere.apps.group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('active_until', models.DateTimeField(blank=True, default=heythere.apps.group.models.blacklist_default_time, null=True)),
                ('blocked_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_blocked_group', to='group.group')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_group', to='group.group')),
            ],
        ),
    ]
