# Generated by Django 3.2.13 on 2022-04-29 06:45

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('group', '0002_group_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_active',
        ),
        migrations.AddField(
            model_name='group',
            name='desired_other_group_member_avg_age_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default=(20, 30), null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(20), django.contrib.postgres.validators.RangeMaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='group',
            name='desired_other_group_member_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='geo_location',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='gps_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='gps_last_check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='hotplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.hotplace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='introduction',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='GroupPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
        ),
    ]
