# Generated by Django 3.2.13 on 2022-05-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20220507_1840'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='group',
            old_name='gps_geo_location',
            new_name='gps_geoinfo',
        ),
    ]
