# Generated by Django 3.2.13 on 2022-05-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20220508_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='register_step_1_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='register_step_2_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='register_step_3_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='register_step_4_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='register_step_5_completed',
            field=models.BooleanField(default=False),
        ),
    ]
