# Generated by Django 3.2.13 on 2022-04-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20220429_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='expires_at',
            new_name='active_until',
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='GroupPhoto',
        ),
    ]
