# Generated by Django 3.2.13 on 2022-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20220627_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofileimage',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='groupprofileimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
