# Generated by Django 3.2.13 on 2022-05-11 09:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc
import heythere.apps.group.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0004_auto_20220508_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='register_step_5_completed',
            new_name='register_step_all_confirmed',
        ),
        migrations.CreateModel(
            name='GroupInvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=heythere.apps.group.models.unique_random_code)),
                ('is_active', models.BooleanField(default=True)),
                ('active_until', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 9, 16, 9, 413929, tzinfo=utc), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
