# Generated by Django 3.2.13 on 2022-04-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20220429_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='geo_location',
            new_name='gps_geo_location',
        ),
    ]
