# Generated by Django 3.2.13 on 2022-05-11 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20220511_0911'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='groupinvitationcode',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='groupinvitationcode',
            name='active_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 11, 59, 24, 238991, tzinfo=utc), null=True),
        ),
    ]
