# Generated by Django 3.2.13 on 2022-04-30 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20220429_0710'),
        ('group', '0005_rename_geo_location_group_gps_geo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_avg_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='member_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='desired_other_group_member_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='hotplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.hotplace'),
        ),
    ]
