# Generated by Django 3.2.13 on 2022-04-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20220429_0710'),
        ('group', '0006_auto_20220430_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hotplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.hotplace'),
        ),
    ]
