# Generated by Django 3.2.13 on 2022-05-11 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20220511_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvitationcode',
            name='active_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 12, 26, 52, 94522, tzinfo=utc), null=True),
        ),
    ]
