# Generated by Django 3.2.13 on 2022-04-30 17:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_group_hotplace'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
