# Generated by Django 3.2.13 on 2022-05-12 01:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_groupinvitationcode_active_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='active_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 12, 1, 55, 23, 584354, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupinvitationcode',
            name='active_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 12, 1, 55, 23, 588335, tzinfo=utc), null=True),
        ),
    ]
