# Generated by Django 3.2.13 on 2022-05-12 02:38

from django.db import migrations, models
import heythere.apps.group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_groupinvitationcode_active_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='active_until',
            field=models.DateTimeField(blank=True, default=heythere.apps.group.models.group_default_time, null=True),
        ),
        migrations.AlterField(
            model_name='groupinvitationcode',
            name='active_until',
            field=models.DateTimeField(blank=True, default=heythere.apps.group.models.invitation_code_default_time, null=True),
        ),
    ]
