# Generated by Django 3.2.13 on 2022-05-12 01:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20220512_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='active_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 1, 51, 7, 774354, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='groupinvitationcode',
            name='active_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 12, 1, 56, 7, 778574, tzinfo=utc), null=True),
        ),
    ]
