# Generated by Django 3.2.13 on 2022-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20220512_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
