# Generated by Django 3.2.13 on 2022-05-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20220515_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofileimage',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
    ]
