# Generated by Django 3.2.13 on 2022-05-15 19:17

from django.db import migrations, models

import heythere.apps.group.models


class Migration(migrations.Migration):
    dependencies = [
        ('group', '0012_alter_groupprofileimage_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofileimage',
            name='image',
            field=models.ImageField(upload_to=heythere.apps.group.models.upload_to),
        ),
    ]
