# Generated by Django 3.2.13 on 2022-05-15 19:17

from django.db import migrations, models
import django_resized.forms
import heythere.apps.group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_alter_groupprofileimage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofileimage',
            name='image_resized',
            field=django_resized.forms.ResizedImageField(crop=None, default=123, force_format=None, keep_meta=True, quality=-1, size=[100, 300], upload_to=heythere.apps.group.models.upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupprofileimage',
            name='image',
            field=models.ImageField(upload_to=heythere.apps.group.models.upload_to),
        ),
    ]
