# Generated by Django 3.2.13 on 2022-05-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_auto_20220515_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofileimage',
            name='image_resized',
        ),
    ]
