# Generated by Django 3.2.13 on 2022-05-18 11:54

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_auto_20220515_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='desired_other_group_member_avg_age_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(20), django.contrib.postgres.validators.RangeMaxValueValidator(50)]),
        ),
    ]
