# Generated by Django 3.2.13 on 2022-06-12 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamChatChannel',
            fields=[
                ('id', models.CharField(editable=False, max_length=256, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamChatChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_chat_channel_member_channel', to='stream.streamchatchannel')),
            ],
        ),
    ]
