version: '3'

volumes:
  heymatch_local_postgres_data: { }
  heymatch_local_postgres_data_backups: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: heymatch_local_django
    container_name: heymatch_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: heymatch_local_postgres
    container_name: heymatch_local_postgres
    volumes:
      - heymatch_local_postgres_data:/var/lib/postgresql/data:Z
      - heymatch_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:7
    container_name: heymatch_local_redis

  celeryworker:
    <<: *django
    image: heymatch_local_celeryworker
    container_name: heymatch_local_celeryworker
    depends_on:
      - postgres
      - redis
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: heymatch_local_celerybeat
    container_name: heymatch_local_celerybeat
    depends_on:
      - postgres
      - redis
    ports: [ ]
    command: /start-celerybeat

  flower:
    <<: *django
    image: heymatch_local_flower
    container_name: heymatch_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
