version: '3'

volumes:
  django_static_volume: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: 238877058502.dkr.ecr.ap-northeast-2.amazonaws.com/heymatch-django-prod
    container_name: django
    platform: linux/x86_64
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "8000:8000"
    command: /start
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: 238877058502.dkr.ecr.ap-northeast-2.amazonaws.com/heymatch-nginx-prod
    container_name: nginx
    volumes:
      - ./compose/production/nginx/conf:/etc/nginx/conf
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf
      - django_static_volume:/app/backend/django_static
    depends_on:
      - django
    ports:
      - "80:80"
