version: '3'

volumes:
  django_static_volume: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: heymatch_production_django
    container_name: django
    platform: linux/x86_64
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "8000:8000"
    command: /start
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: heymatch_production_nginx
    container_name: nginx
    volumes:
      - ./compose/production/nginx/conf:/etc/nginx/conf
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf
      - django_static_volume:/app/backend/django_static
    depends_on:
      - django
    ports:
      - "80:80"
