version: '3'

volumes:
  django_static_volume:
  django_log_volume:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: heymatch_production_django
    container_name: heymatch_production_django
    platform: linux/x86_64
    volumes:
      - .:/app:z
      - django_static_volume:/app/staticfiles
      - django_log_volume:/var/log
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "8000:8000"
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: heymatch_production_nginx
    container_name: heymatch_production_nginx
    volumes:
      - ./compose/production/nginx/conf:/etc/nginx/conf
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf
      - django_static_volume:/app/staticfiles
    depends_on:
      - django
    ports:
      - "80:80"

  redis:
    image: redis:7
    container_name: heymatch_production_redis

  celeryworker:
    <<: *django
    image: heymatch_production_celeryworker
    container_name: heymatch_production_celeryworker
    depends_on:
      - redis
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: heymatch_production_celerybeat
    container_name: heymatch_production_celerybeat
    depends_on:
      - redis
    ports: [ ]
    command: /start-celerybeat

  flower:
    <<: *django
    image: heymatch_production_flower
    container_name: heymatch_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
