version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  django_static_volume: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: heythere_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: heythere_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: heythere_production_nginx
    container_name: nginx
    volumes:
      - ./compose/production/nginx/conf:/etc/nginx/conf
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf
      - django_static_volume:/app/backend/staticfiles
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"

  celeryworker:
    <<: *django
    image: heythere_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: heythere_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: heythere_production_flower
    command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
