# Generated by Django 3.2.13 on 2022-05-23 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0014_alter_group_desired_other_group_member_avg_age_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_messages_drf.auditmodel')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('unread', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_request_receiver_group', to='group.group')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_request_sender_group', to='group.group')),
            ],
            bases=('django_messages_drf.auditmodel',),
        ),
    ]
