# Generated by Django 3.2.13 on 2022-06-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='denied',
            field=models.BooleanField(default=False),
        ),
    ]
