# Generated by Django 3.2.13 on 2022-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('active_until', models.DateTimeField()),
            ],
        ),
    ]
