# Generated by Django 3.2.13 on 2022-09-01 05:12

from django.db import migrations, models
import heythere.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=heythere.apps.user.models.generate_random_username, max_length=10, unique=True),
        ),
    ]
