# Generated by Django 3.2.13 on 2022-05-07 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(155), django.core.validators.MaxValueValidator(195)]),
        ),
    ]
