# Generated by Django 3.2.13 on 2022-04-29 06:45

from django.db import migrations, models
import heythere.apps.user.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220427_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[heythere.apps.user.models.validate_birth_year]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True, validators=[heythere.apps.user.models.validate_height_cm]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='workplace',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
