# Generated by Django 3.2.13 on 2022-04-29 06:45

import django.contrib.auth.validators
import django.contrib.postgres.fields.ranges
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220427_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height_cm',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default=(20, 30), null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(100), django.contrib.postgres.validators.RangeMaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='workplace',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
