# Generated by Django 3.2.13 on 2022-05-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20220511_0911'),
        ('user', '0002_auto_20220507_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='group.group'),
        ),
    ]
