# Generated by Django 3.2.13 on 2022-05-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20220511_1154'),
        ('user', '0003_alter_user_joined_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='group.group'),
        ),
    ]
