# Generated by Django 3.2.13 on 2022-04-30 14:36

import birthday.fields
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220429_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=birthday.fields.BirthdayField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height_cm',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default=(20, 30), null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(100), django.contrib.postgres.validators.RangeMaxValueValidator(250)]),
        ),
    ]
