# Generated by Django 3.2.13 on 2022-04-30 14:43

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220430_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_cm',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(100), django.contrib.postgres.validators.RangeMaxValueValidator(250)]),
        ),
    ]
