# Generated by Django 3.2.13 on 2022-11-09 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED')], default='WAITING', max_length=48)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stream_channel_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('stream_channel_cid', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('stream_channel_type', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('receiver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_request_receiver_group', to='group.group')),
                ('sender_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_request_sender_group', to='group.group')),
            ],
        ),
    ]
