# Generated by Django 3.2.13 on 2022-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
