# Generated by Django 3.2.13 on 2022-11-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchrequest',
            old_name='receiver',
            new_name='receiver_group',
        ),
        migrations.RenameField(
            model_name='matchrequest',
            old_name='sender',
            new_name='sender_group',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='denied',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='unread',
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED')], default='WAITING', max_length=48),
        ),
    ]
