# Generated by Django 3.2.13 on 2023-05-09 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20230508_2220'),
        ('match', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatchrequest',
            name='receiver_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='group.groupv2'),
        ),
        migrations.AlterField(
            model_name='historicalmatchrequest',
            name='sender_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='group.groupv2'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='receiver_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_request_receiver_group', to='group.groupv2'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='sender_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_request_sender_group', to='group.groupv2'),
        ),
    ]
