# Generated by Django 3.2.13 on 2022-11-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatchrequest',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='WAITING', max_length=48),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='WAITING', max_length=48),
        ),
    ]
