# Generated by Django 3.2.13 on 2022-11-02 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20221102_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrequest',
            name='uuid',
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
