# Generated by Django 3.2.13 on 2022-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20221102_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='stream_channel_cid',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='stream_channel_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='stream_channel_type',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
