# Generated by Django 3.2.13 on 2022-11-20 03:57

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleStoreValidatedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=48)),
                ('transaction_id', models.CharField(max_length=48, unique=True)),
                ('original_transaction_id', models.CharField(max_length=48)),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField()),
                ('receipt_creation_date_ms', models.CharField(max_length=32)),
                ('request_date_ms', models.CharField(max_length=32)),
                ('purchase_date_ms', models.CharField(max_length=32)),
                ('original_purchase_date_ms', models.CharField(max_length=32)),
                ('is_trial_period', models.BooleanField()),
                ('in_app_ownership_type', models.CharField(max_length=32)),
                ('environment', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FreePassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('product_id', models.CharField(max_length=128, unique=True)),
                ('price_in_krw', models.IntegerField()),
                ('free_pass_duration_in_hour', models.IntegerField()),
                ('best_deal_check', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUserPurchase',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('platform', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=8)),
                ('purchase_processed', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical user purchase',
                'verbose_name_plural': 'historical user purchases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlayStoreValidatedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=48, unique=True)),
                ('packageName', models.CharField(max_length=48)),
                ('productId', models.CharField(max_length=48)),
                ('quantity', models.IntegerField()),
                ('purchaseToken', models.TextField(max_length=250)),
                ('purchaseTimeMillis', models.CharField(max_length=32)),
                ('purchaseState', models.IntegerField()),
                ('consumptionState', models.IntegerField()),
                ('purchaseType', models.IntegerField()),
                ('acknowledgementState', models.IntegerField()),
                ('kind', models.CharField(max_length=48)),
                ('regionCode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PointItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('product_id', models.CharField(max_length=128, unique=True)),
                ('price_in_krw', models.IntegerField()),
                ('default_point', models.IntegerField()),
                ('bonus_point', models.IntegerField(blank=True, default=0, null=True)),
                ('best_deal_check', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=8)),
                ('purchase_processed', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('apple_store_receipt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.applestorevalidatedreceipt')),
                ('free_pass_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.freepassitem')),
                ('play_store_receipt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.playstorevalidatedreceipt')),
                ('point_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.pointitem')),
            ],
        ),
    ]
