# Generated by Django 3.2.13 on 2022-10-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreePassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('product_id', models.CharField(max_length=128, unique=True)),
                ('price_in_krw', models.IntegerField()),
                ('free_pass_duration_in_hour', models.IntegerField()),
                ('best_deal_check', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('product_id', models.CharField(max_length=128, unique=True)),
                ('price_in_krw', models.IntegerField()),
                ('default_point', models.IntegerField()),
                ('bonus_point', models.IntegerField(blank=True, default=0, null=True)),
                ('best_deal_check', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
