# Generated by Django 3.2.13 on 2023-05-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserpurchase',
            name='apple_store_receipt',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payment.applestorevalidatedreceipt'),
        ),
        migrations.AddField(
            model_name='historicaluserpurchase',
            name='free_pass_item',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payment.freepassitem'),
        ),
    ]
