# Generated by Django 3.2.13 on 2022-11-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchase',
            name='free_pass_item',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.freepassitem'),
        ),
        migrations.AddField(
            model_name='userpurchase',
            name='point_item',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.pointitem'),
        ),
    ]
