# Generated by Django 3.2.13 on 2022-10-24 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleStoreReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayStoreReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseTimeMillis', models.CharField(max_length=32)),
                ('purchaseState', models.IntegerField()),
                ('consumptionState', models.IntegerField()),
                ('developerPayload', models.CharField(max_length=120)),
                ('orderId', models.CharField(max_length=48)),
                ('purchaseType', models.IntegerField()),
                ('acknowledgementState', models.IntegerField()),
                ('kind', models.CharField(max_length=48)),
                ('regionCode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='UserReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=8)),
                ('apple_store_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.applestorereceipt')),
                ('play_store_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.playstorereceipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
