# Generated by Django 3.2.13 on 2022-10-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpurchase',
            old_name='UserPurchase',
            new_name='user',
        ),
    ]
