# Generated by Django 3.2.13 on 2023-08-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpointconsumptionhistory',
            name='consumed_reason',
            field=models.CharField(choices=[('SEND_MATCH_REQUEST', 'Send Match Request'), ('OPENED_PROFILE_PHOTO', 'Opened Profile Photo')], max_length=128),
        ),
    ]
