# Generated by Django 3.2.13 on 2022-11-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20221101_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='apple_store_receipt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.applestorevalidatedreceipt'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='free_pass_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.freepassitem'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='play_store_receipt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.playstorevalidatedreceipt'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='point_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.pointitem'),
        ),
    ]
