# Generated by Django 3.2.13 on 2022-11-23 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserpurchase',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'Ios')], max_length=8),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'Ios')], max_length=8),
        ),
        migrations.CreateModel(
            name='UserPointConsumptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_point', models.IntegerField()),
                ('consumed_reason', models.CharField(choices=[('SEND_MATCH_REQUEST', 'Send Match Request')], max_length=128)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_point_consumption_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
