# Generated by Django 3.2.13 on 2022-11-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20221123_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applestorevalidatedreceipt',
            name='environment',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applestorevalidatedreceipt',
            name='in_app_ownership_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applestorevalidatedreceipt',
            name='is_trial_period',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playstorevalidatedreceipt',
            name='acknowledgementState',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playstorevalidatedreceipt',
            name='kind',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='playstorevalidatedreceipt',
            name='purchaseType',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playstorevalidatedreceipt',
            name='regionCode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
