# Generated by Django 3.2.13 on 2022-11-13 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_userpurchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
