# Generated by Django 3.2.13 on 2023-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_userpointconsumptionhistory_consumed_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpointconsumptionhistory',
            name='consumed_reason',
            field=models.CharField(choices=[('SEND_MATCH_REQUEST', 'Send Match Request'), ('OPENED_PROFILE_PHOTO', 'Opened Profile Photo'), ('OPENED_PROFILE_PHOTO_BY_ADS', 'Opened Profile Photo By Ads')], max_length=128),
        ),
    ]
