# Generated by Django 3.2.13 on 2022-12-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20221202_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applestorevalidatedreceipt',
            name='original_purchase_date_ms',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applestorevalidatedreceipt',
            name='purchase_date_ms',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applestorevalidatedreceipt',
            name='receipt_creation_date_ms',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applestorevalidatedreceipt',
            name='request_date_ms',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applestorevalidatedreceipt',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
