# Generated by Django 3.2.13 on 2022-10-12 16:26

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import heymatch.apps.group.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_geoinfo', heymatch.apps.group.models.EncryptedGeoLocationField(max_length=100)),
                ('gps_checked', models.BooleanField(default=False)),
                ('gps_last_check_time', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title of Group')),
                ('introduction', models.TextField(max_length=500)),
                ('male_member_number', models.IntegerField(blank=True, null=True)),
                ('female_member_number', models.IntegerField(blank=True, null=True)),
                ('member_average_age', models.IntegerField(blank=True, null=True)),
                ('desired_other_group_member_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('desired_other_group_member_avg_age_range', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(20), django.contrib.postgres.validators.RangeMaxValueValidator(50)])),
                ('register_step_1_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('register_step_2_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('register_step_3_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('register_step_4_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('register_step_all_confirmed', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_until', models.DateTimeField(blank=True, default=heymatch.apps.group.models.group_default_time, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('active_until', models.DateTimeField(blank=True, default=heymatch.apps.group.models.blacklist_default_time, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=heymatch.apps.group.models.unique_random_code)),
                ('is_active', models.BooleanField(default=True)),
                ('active_until', models.DateTimeField(blank=True, default=heymatch.apps.group.models.invitation_code_default_time, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.ImageField(upload_to=heymatch.apps.group.models.upload_to)),
                ('image_blurred', models.ImageField(upload_to=heymatch.apps.group.models.upload_to)),
                ('thumbnail', models.ImageField(upload_to=heymatch.apps.group.models.upload_to)),
                ('thumbnail_blurred', models.ImageField(upload_to=heymatch.apps.group.models.upload_to)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_profile_images', to='group.group')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
