# Generated by Django 3.2.13 on 2022-11-20 03:57

from django.db import migrations, models
import django.db.models.deletion
import heymatch.apps.group.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_geoinfo', heymatch.apps.group.models.EncryptedGeoLocationField(max_length=100)),
                ('title', models.CharField(max_length=100, verbose_name='Title of Group')),
                ('introduction', models.TextField(max_length=500)),
                ('male_member_number', models.IntegerField(blank=True, null=True)),
                ('female_member_number', models.IntegerField(blank=True, null=True)),
                ('member_average_age', models.IntegerField(blank=True, null=True)),
                ('match_point', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.ImageField(upload_to=heymatch.apps.group.models.upload_to)),
                ('image_blurred', models.ImageField(upload_to=heymatch.apps.group.models.upload_to)),
                ('thumbnail', models.ImageField(upload_to=heymatch.apps.group.models.upload_to)),
                ('thumbnail_blurred', models.ImageField(upload_to=heymatch.apps.group.models.upload_to)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('gps_geoinfo', heymatch.apps.group.models.EncryptedGeoLocationField(max_length=100)),
                ('title', models.CharField(max_length=100, verbose_name='Title of Group')),
                ('introduction', models.TextField(max_length=500)),
                ('male_member_number', models.IntegerField(blank=True, null=True)),
                ('female_member_number', models.IntegerField(blank=True, null=True)),
                ('member_average_age', models.IntegerField(blank=True, null=True)),
                ('match_point', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical group',
                'verbose_name_plural': 'historical groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGroupProfileImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.TextField(max_length=100)),
                ('image_blurred', models.TextField(max_length=100)),
                ('thumbnail', models.TextField(max_length=100)),
                ('thumbnail_blurred', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='group.group')),
            ],
            options={
                'verbose_name': 'historical group profile image',
                'verbose_name_plural': 'historical group profile images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
