# Generated by Django 3.2.13 on 2022-10-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='match_point',
            field=models.IntegerField(default=1),
        ),
    ]
