# Generated by Django 3.2.13 on 2023-03-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupv2',
            name='gps_geoinfo',
        ),
        migrations.RemoveField(
            model_name='historicalgroupv2',
            name='gps_geoinfo',
        ),
    ]
