# Generated by Django 3.2.13 on 2023-03-23 17:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='gps_point',
            field=django.contrib.gis.db.models.fields.PointField(default=1, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='gps_point',
            field=django.contrib.gis.db.models.fields.PointField(default=10, srid=4326),
            preserve_default=False,
        ),
    ]
