# Generated by Django 3.2.13 on 2022-11-30 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('PROCESSED', 'Processed')], default='REPORTED', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_by_user', to=settings.AUTH_USER_MODEL)),
                ('reported_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group')),
            ],
        ),
    ]
