# Generated by Django 3.2.13 on 2022-09-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='female_member_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='male_member_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='member_average_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
