# Generated by Django 3.2.13 on 2023-04-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupv2',
            name='meetup_timerange',
            field=models.CharField(blank=True, choices=[('lunch', 'Lunch'), ('afternoon', 'Afternoon'), ('dinner', 'Dinner'), ('night', 'Night'), ('not_sure', 'Not Sure')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='meetup_timerange',
            field=models.CharField(blank=True, choices=[('lunch', 'Lunch'), ('afternoon', 'Afternoon'), ('dinner', 'Dinner'), ('night', 'Night'), ('not_sure', 'Not Sure')], max_length=20, null=True),
        ),
    ]
