# Generated by Django 3.2.13 on 2023-08-09 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofilephotopurchased',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicalgroupprofilephotopurchased',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
