# Generated by Django 3.2.13 on 2023-05-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupv2',
            old_name='meetup_address',
            new_name='meetup_place_address',
        ),
        migrations.RenameField(
            model_name='historicalgroupv2',
            old_name='meetup_address',
            new_name='meetup_place_address',
        ),
        migrations.AddField(
            model_name='groupv2',
            name='meetup_place_title',
            field=models.CharField(default='신사동 주민센터', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='meetup_place_title',
            field=models.CharField(default='신사동 주민센터', max_length=250),
            preserve_default=False,
        ),
    ]
