# Generated by Django 3.2.13 on 2023-03-25 06:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20230325_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupv2',
            name='gps_point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='gps_point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
