# Generated by Django 3.2.13 on 2022-09-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0001_initial'),
        ('group', '0003_auto_20220923_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hotplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='hotplace.hotplace'),
        ),
        migrations.AlterField(
            model_name='groupprofileimage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_profile_images', to='group.group'),
        ),
    ]
