# Generated by Django 3.2.13 on 2022-12-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_reportedgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofileimage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_profile_images', to='group.group'),
        ),
        migrations.AlterField(
            model_name='reportedgroup',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportedgroup',
            name='reported_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='group.group'),
        ),
    ]
