# Generated by Django 3.2.13 on 2023-08-20 08:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20230809_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘 애교가 많아요'), ('A_LOT_OF_PLAYFULNESS', '😝 장난기가 많아요'), ('INTERNATIONAL', '🌏 다국적이에요'), ('A_LOT_OF_ACTIVENESS', '😃 활달해요'), ('TENDS_TO_BE_QUIET', '😷 조용한 편이에요'), ('A_LOT_OF_SHYNESS', '🙈 수줍음이 많아요'), ('NICE_BODY_SHAPE', '👍 몸매가 좋아요'), ('WE_ARE_HANDSOME', '🤩 잘생겼어요'), ('WE_ARE_PRETTY', '😍 예뻐요'), ('WE_ARE_GOOD_LOOKING', '☺️ 훈훈해요'), ('FASHION_PEOPLE', '🕶️ 패셔니스타'), ('WE_ARE_KING', '👑 이 구역의 왕은 우리야'), ('WE_LIKE_SPORTS', '💪 운동을 좋아해요'), ('A_LOT_OF_LAUGHING', '🤣 웃음이 많아요'), ('GOOD_AT_TALKING', '💬 대화를 잘해요'), ('WE_ARE_HUMOROUS', '😂 유머러스해요')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='groupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷 와인 좋아해요'), ('WE_LIKE_BEER', '🍺 맥주 좋아해요'), ('WE_LIKE_MEAT', '🍖 고기 먹어요'), ('WE_LIKE_SOJU', '💚 소주 좋아해요'), ('WE_LIKE_SOUP', '🍲 국물 안주 먹어요'), ('LETS_PLAY_ALCOHOL_GAME', '🎮 술게임해요'), ('LETS_TALK', '💬 차분히 대화해요'), ('WE_EAT_ANYTHING', '🤔 아무거나 먹어요'), ('WE_EAT_CHICKEN', '🍗 치킨 먹어요'), ('LETS_PLAY_HOT', '🔥 화끈하게 놀아요'), ('PLAY_UNTIL_END', '💪 끝까지 달려요'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻 1차로만 가볍게 놀아요'), ('DRINK_MAKGULI', '☂️비 오는 날은 막걸리')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘 애교가 많아요'), ('A_LOT_OF_PLAYFULNESS', '😝 장난기가 많아요'), ('INTERNATIONAL', '🌏 다국적이에요'), ('A_LOT_OF_ACTIVENESS', '😃 활달해요'), ('TENDS_TO_BE_QUIET', '😷 조용한 편이에요'), ('A_LOT_OF_SHYNESS', '🙈 수줍음이 많아요'), ('NICE_BODY_SHAPE', '👍 몸매가 좋아요'), ('WE_ARE_HANDSOME', '🤩 잘생겼어요'), ('WE_ARE_PRETTY', '😍 예뻐요'), ('WE_ARE_GOOD_LOOKING', '☺️ 훈훈해요'), ('FASHION_PEOPLE', '🕶️ 패셔니스타'), ('WE_ARE_KING', '👑 이 구역의 왕은 우리야'), ('WE_LIKE_SPORTS', '💪 운동을 좋아해요'), ('A_LOT_OF_LAUGHING', '🤣 웃음이 많아요'), ('GOOD_AT_TALKING', '💬 대화를 잘해요'), ('WE_ARE_HUMOROUS', '😂 유머러스해요')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷 와인 좋아해요'), ('WE_LIKE_BEER', '🍺 맥주 좋아해요'), ('WE_LIKE_MEAT', '🍖 고기 먹어요'), ('WE_LIKE_SOJU', '💚 소주 좋아해요'), ('WE_LIKE_SOUP', '🍲 국물 안주 먹어요'), ('LETS_PLAY_ALCOHOL_GAME', '🎮 술게임해요'), ('LETS_TALK', '💬 차분히 대화해요'), ('WE_EAT_ANYTHING', '🤔 아무거나 먹어요'), ('WE_EAT_CHICKEN', '🍗 치킨 먹어요'), ('LETS_PLAY_HOT', '🔥 화끈하게 놀아요'), ('PLAY_UNTIL_END', '💪 끝까지 달려요'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻 1차로만 가볍게 놀아요'), ('DRINK_MAKGULI', '☂️비 오는 날은 막걸리')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
    ]
