# Generated by Django 3.2.13 on 2023-06-05 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_auto_20230521_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='photo_point',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='photo_point',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groupv2',
            name='match_point',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='match_point',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='HistoricalGroupProfilePhotoPurchased',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('buyer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='group.groupv2')),
            ],
            options={
                'verbose_name': 'historical group profile photo purchased',
                'verbose_name_plural': 'historical group profile photo purchaseds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GroupProfilePhotoPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_group_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_group_seller', to='group.groupv2')),
            ],
        ),
    ]
