# Generated by Django 3.2.13 on 2023-05-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20230412_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='member_avg_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='member_avg_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
