# Generated by Django 3.2.13 on 2022-10-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20220923_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='introduction',
            field=models.TextField(default='example', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
