# Generated by Django 3.2.13 on 2023-03-27 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20230325_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupv2',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
