# Generated by Django 3.2.13 on 2023-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20230507_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='member_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='member_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
