# Generated by Django 3.2.13 on 2023-08-24 07:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20230822_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘애교가 많아요,#80F2A1FF'), ('A_LOT_OF_PLAYFULNESS', '😝장난기가 많아요,#8083F8FF'), ('INTERNATIONAL', '🌏다국적이에요,#80BAEC4F'), ('A_LOT_OF_ACTIVENESS', '😃활달해요,#8065C079'), ('TENDS_TO_BE_QUIET', '😷조용한 편이에요,#80BF8CFF'), ('A_LOT_OF_SHYNESS', '🙈수줍음이 많아요,#80FF7A7A'), ('NICE_BODY_SHAPE', '👍몸매가 좋아요,#80FFBF43'), ('WE_ARE_HANDSOME', '🤩잘생겼어요,#806BA6FF'), ('WE_ARE_PRETTY', '😍예뻐요,#80FF43EC'), ('WE_ARE_GOOD_LOOKING', '☺️훈훈해요,#800042F0'), ('FASHION_PEOPLE', '🕶️패셔니스타,#80AA3ADE'), ('WE_ARE_KING', '👑이 구역의 왕은 우리야,#807FFF7C'), ('WE_LIKE_SPORTS', '💪운동을 좋아해요,#80FFEA32'), ('A_LOT_OF_LAUGHING', '🤣웃음이 많아요,#802DAC00'), ('GOOD_AT_TALKING', '💬대화를 잘해요,#80D9D9D9'), ('WE_ARE_HUMOROUS', '😂유머러스해요,#80E00388')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='groupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷와인 좋아해요,#80DB5555'), ('WE_LIKE_BEER', '🍺맥주 좋아해요,#80FFB800'), ('WE_LIKE_MEAT', '🍖고기 먹어요,#80FFA15E'), ('WE_LIKE_SOJU', '💚소주 좋아해요,#8077FF37'), ('WE_LIKE_SOUP', '🍲국물 안주 먹어요,#806CFFF6'), ('LETS_PLAY_ALCOHOL_GAME', '🎮술게임해요,#80D356FF'), ('LETS_TALK', '💬차분히 대화해요,#80D9D9D9'), ('WE_EAT_ANYTHING', '🤔아무거나 먹어요,#80F8A23E'), ('WE_EAT_CHICKEN', '🍗치킨 먹어요,#80FF6262'), ('LETS_PLAY_HOT', '🔥화끈하게 놀아요,#80FA2C2C'), ('PLAY_UNTIL_END', '💪끝까지 달려요,#807B49E4'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻1차로만 가볍게 놀아요,#80DBFF00'), ('DRINK_MAKGULI', '☂️비 오는 날은 막걸리,#8000A3D7')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘애교가 많아요,#80F2A1FF'), ('A_LOT_OF_PLAYFULNESS', '😝장난기가 많아요,#8083F8FF'), ('INTERNATIONAL', '🌏다국적이에요,#80BAEC4F'), ('A_LOT_OF_ACTIVENESS', '😃활달해요,#8065C079'), ('TENDS_TO_BE_QUIET', '😷조용한 편이에요,#80BF8CFF'), ('A_LOT_OF_SHYNESS', '🙈수줍음이 많아요,#80FF7A7A'), ('NICE_BODY_SHAPE', '👍몸매가 좋아요,#80FFBF43'), ('WE_ARE_HANDSOME', '🤩잘생겼어요,#806BA6FF'), ('WE_ARE_PRETTY', '😍예뻐요,#80FF43EC'), ('WE_ARE_GOOD_LOOKING', '☺️훈훈해요,#800042F0'), ('FASHION_PEOPLE', '🕶️패셔니스타,#80AA3ADE'), ('WE_ARE_KING', '👑이 구역의 왕은 우리야,#807FFF7C'), ('WE_LIKE_SPORTS', '💪운동을 좋아해요,#80FFEA32'), ('A_LOT_OF_LAUGHING', '🤣웃음이 많아요,#802DAC00'), ('GOOD_AT_TALKING', '💬대화를 잘해요,#80D9D9D9'), ('WE_ARE_HUMOROUS', '😂유머러스해요,#80E00388')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷와인 좋아해요,#80DB5555'), ('WE_LIKE_BEER', '🍺맥주 좋아해요,#80FFB800'), ('WE_LIKE_MEAT', '🍖고기 먹어요,#80FFA15E'), ('WE_LIKE_SOJU', '💚소주 좋아해요,#8077FF37'), ('WE_LIKE_SOUP', '🍲국물 안주 먹어요,#806CFFF6'), ('LETS_PLAY_ALCOHOL_GAME', '🎮술게임해요,#80D356FF'), ('LETS_TALK', '💬차분히 대화해요,#80D9D9D9'), ('WE_EAT_ANYTHING', '🤔아무거나 먹어요,#80F8A23E'), ('WE_EAT_CHICKEN', '🍗치킨 먹어요,#80FF6262'), ('LETS_PLAY_HOT', '🔥화끈하게 놀아요,#80FA2C2C'), ('PLAY_UNTIL_END', '💪끝까지 달려요,#807B49E4'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻1차로만 가볍게 놀아요,#80DBFF00'), ('DRINK_MAKGULI', '☂️비 오는 날은 막걸리,#8000A3D7')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
    ]
