# Generated by Django 3.2.13 on 2023-08-24 07:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20230824_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘애교가 많아요,F2A1FF80'), ('A_LOT_OF_PLAYFULNESS', '😝장난기가 많아요,83F8FF80'), ('INTERNATIONAL', '🌏다국적이에요,BAEC4F80'), ('A_LOT_OF_ACTIVENESS', '😃활달해요,65C07980'), ('TENDS_TO_BE_QUIET', '😷조용한 편이에요,BF8CFF80'), ('A_LOT_OF_SHYNESS', '🙈수줍음이 많아요,FF7A7A80'), ('NICE_BODY_SHAPE', '👍몸매가 좋아요,FFC45380'), ('WE_ARE_HANDSOME', '🤩잘생겼어요,8FBCFF80'), ('WE_ARE_PRETTY', '😍예뻐요,FF62EF80'), ('WE_ARE_GOOD_LOOKING', '☺️훈훈해요,5785FF80'), ('FASHION_PEOPLE', '🕶️패셔니스타,D48EFF80'), ('WE_ARE_KING', '👑이 구역의 왕은 우리야,89FF8780'), ('WE_LIKE_SPORTS', '💪운동을 좋아해요,65FF7E80'), ('A_LOT_OF_LAUGHING', '🤣웃음이 많아요,71FFE580'), ('GOOD_AT_TALKING', '💬대화를 잘해요,CDCDCD80'), ('WE_ARE_HUMOROUS', '😂유머러스해요,FF81E380')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='groupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷와인 좋아해요,FF818180'), ('WE_LIKE_BEER', '🍺맥주 좋아해요,FFCD4E80'), ('WE_LIKE_MEAT', '🍖고기 먹어요,FFB07680'), ('WE_LIKE_SOJU', '💚소주 좋아해요,93FF6080'), ('WE_LIKE_SOUP', '🍲국물 안주 먹어요,7EFFF780'), ('LETS_PLAY_ALCOHOL_GAME', '🎮술게임해요,DC79FF80'), ('LETS_TALK', '💬차분히 대화해요,E1DEDE80'), ('WE_EAT_ANYTHING', '🤔아무거나 먹어요,FABB7080'), ('WE_EAT_CHICKEN', '🍗치킨 먹어요,FFD99F80'), ('LETS_PLAY_HOT', '🔥화끈하게 놀아요,FF6D6D80'), ('PLAY_UNTIL_END', '💪끝까지 달려요,9365F480'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻1차로만 가볍게 놀아요,E2FF2D80'), ('DRINK_MAKGULI', '☂️비 오는 날은 막걸리,73DDFF80')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘애교가 많아요,F2A1FF80'), ('A_LOT_OF_PLAYFULNESS', '😝장난기가 많아요,83F8FF80'), ('INTERNATIONAL', '🌏다국적이에요,BAEC4F80'), ('A_LOT_OF_ACTIVENESS', '😃활달해요,65C07980'), ('TENDS_TO_BE_QUIET', '😷조용한 편이에요,BF8CFF80'), ('A_LOT_OF_SHYNESS', '🙈수줍음이 많아요,FF7A7A80'), ('NICE_BODY_SHAPE', '👍몸매가 좋아요,FFC45380'), ('WE_ARE_HANDSOME', '🤩잘생겼어요,8FBCFF80'), ('WE_ARE_PRETTY', '😍예뻐요,FF62EF80'), ('WE_ARE_GOOD_LOOKING', '☺️훈훈해요,5785FF80'), ('FASHION_PEOPLE', '🕶️패셔니스타,D48EFF80'), ('WE_ARE_KING', '👑이 구역의 왕은 우리야,89FF8780'), ('WE_LIKE_SPORTS', '💪운동을 좋아해요,65FF7E80'), ('A_LOT_OF_LAUGHING', '🤣웃음이 많아요,71FFE580'), ('GOOD_AT_TALKING', '💬대화를 잘해요,CDCDCD80'), ('WE_ARE_HUMOROUS', '😂유머러스해요,FF81E380')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷와인 좋아해요,FF818180'), ('WE_LIKE_BEER', '🍺맥주 좋아해요,FFCD4E80'), ('WE_LIKE_MEAT', '🍖고기 먹어요,FFB07680'), ('WE_LIKE_SOJU', '💚소주 좋아해요,93FF6080'), ('WE_LIKE_SOUP', '🍲국물 안주 먹어요,7EFFF780'), ('LETS_PLAY_ALCOHOL_GAME', '🎮술게임해요,DC79FF80'), ('LETS_TALK', '💬차분히 대화해요,E1DEDE80'), ('WE_EAT_ANYTHING', '🤔아무거나 먹어요,FABB7080'), ('WE_EAT_CHICKEN', '🍗치킨 먹어요,FFD99F80'), ('LETS_PLAY_HOT', '🔥화끈하게 놀아요,FF6D6D80'), ('PLAY_UNTIL_END', '💪끝까지 달려요,9365F480'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻1차로만 가볍게 놀아요,E2FF2D80'), ('DRINK_MAKGULI', '☂️비 오는 날은 막걸리,73DDFF80')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
    ]
