# Generated by Django 3.2.13 on 2023-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20230507_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='gps_address',
            field=models.CharField(default='서울특별시 강남구 압구정동', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='gps_address',
            field=models.CharField(default='서울특별시 강남구 압구정동', max_length=250),
            preserve_default=False,
        ),
    ]
