# Generated by Django 3.2.13 on 2023-08-24 07:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20230824_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘애교가 많아요/rgba(242,161,255,0.5)'), ('A_LOT_OF_PLAYFULNESS', '😝장난기가 많아요/rgba(131,248,255,0.5)'), ('INTERNATIONAL', '🌏다국적이에요/rgba(188,236,79,0.5)'), ('A_LOT_OF_ACTIVENESS', '😃활달해요/rgba(101,192,121,0.5)'), ('TENDS_TO_BE_QUIET', '😷조용한 편이에요/rgba(191,140,255,0.5)'), ('A_LOT_OF_SHYNESS', '🙈수줍음이 많아요/rgba(255,122,122,0.5)'), ('NICE_BODY_SHAPE', '👍몸매가 좋아요/rgba(255,196,83,0.5)'), ('WE_ARE_HANDSOME', '🤩잘생겼어요/rgba(143,188,255,0.5)'), ('WE_ARE_PRETTY', '😍예뻐요/rgba(255,98,239,0.5)'), ('WE_ARE_GOOD_LOOKING', '☺️훈훈해요/rgba(87,133,255,0.5)'), ('FASHION_PEOPLE', '🕶️패셔니스타/rgba(212,142,255,0.5)'), ('WE_ARE_KING', '👑이 구역의 왕은 우리야/rgba(137,255,135,0.5)'), ('WE_LIKE_SPORTS', '💪운동을 좋아해요/rgba(101,255,126,0.5)'), ('A_LOT_OF_LAUGHING', '🤣웃음이 많아요/rgba(113,255,229,0.5)'), ('GOOD_AT_TALKING', '💬대화를 잘해요/rgba(205,205,205,0.5)'), ('WE_ARE_HUMOROUS', '😂유머러스해요/rgba(255,129,227,0.5)')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='groupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷와인 좋아해요/rgba(255,129,129,0.5)'), ('WE_LIKE_BEER', '🍺맥주 좋아해요/rgba(255,205,78,0.5)'), ('WE_LIKE_MEAT', '🍖고기 먹어요/rgba(255,176,118,0.5)'), ('WE_LIKE_SOJU', '💚소주 좋아해요/rgba(147,255,96,0.5)'), ('WE_LIKE_SOUP', '🍲국물 안주 먹어요/rgba(126,255,247,0.5)'), ('LETS_PLAY_ALCOHOL_GAME', '🎮술게임해요/rgba(220,121,255,0.5)'), ('LETS_TALK', '💬차분히 대화해요/rgba(255,222,222,0.8)'), ('WE_EAT_ANYTHING', '🤔아무거나 먹어요/rgba(250,187,112,0.5)'), ('WE_EAT_CHICKEN', '🍗치킨 먹어요/rgba(255,217,159,0.8)'), ('LETS_PLAY_HOT', '🔥화끈하게 놀아요/rgba(255,109,109,0.5)'), ('PLAY_UNTIL_END', '💪끝까지 달려요/rgba(147,101,244,0.5)'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻1차로만 가볍게 놀아요/rgba(226,255,45,0.5)'), ('DRINK_MAKGULI', '☂️비 오는 날은 막걸리/rgba(115,221,255,0.5)')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘애교가 많아요/rgba(242,161,255,0.5)'), ('A_LOT_OF_PLAYFULNESS', '😝장난기가 많아요/rgba(131,248,255,0.5)'), ('INTERNATIONAL', '🌏다국적이에요/rgba(188,236,79,0.5)'), ('A_LOT_OF_ACTIVENESS', '😃활달해요/rgba(101,192,121,0.5)'), ('TENDS_TO_BE_QUIET', '😷조용한 편이에요/rgba(191,140,255,0.5)'), ('A_LOT_OF_SHYNESS', '🙈수줍음이 많아요/rgba(255,122,122,0.5)'), ('NICE_BODY_SHAPE', '👍몸매가 좋아요/rgba(255,196,83,0.5)'), ('WE_ARE_HANDSOME', '🤩잘생겼어요/rgba(143,188,255,0.5)'), ('WE_ARE_PRETTY', '😍예뻐요/rgba(255,98,239,0.5)'), ('WE_ARE_GOOD_LOOKING', '☺️훈훈해요/rgba(87,133,255,0.5)'), ('FASHION_PEOPLE', '🕶️패셔니스타/rgba(212,142,255,0.5)'), ('WE_ARE_KING', '👑이 구역의 왕은 우리야/rgba(137,255,135,0.5)'), ('WE_LIKE_SPORTS', '💪운동을 좋아해요/rgba(101,255,126,0.5)'), ('A_LOT_OF_LAUGHING', '🤣웃음이 많아요/rgba(113,255,229,0.5)'), ('GOOD_AT_TALKING', '💬대화를 잘해요/rgba(205,205,205,0.5)'), ('WE_ARE_HUMOROUS', '😂유머러스해요/rgba(255,129,227,0.5)')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷와인 좋아해요/rgba(255,129,129,0.5)'), ('WE_LIKE_BEER', '🍺맥주 좋아해요/rgba(255,205,78,0.5)'), ('WE_LIKE_MEAT', '🍖고기 먹어요/rgba(255,176,118,0.5)'), ('WE_LIKE_SOJU', '💚소주 좋아해요/rgba(147,255,96,0.5)'), ('WE_LIKE_SOUP', '🍲국물 안주 먹어요/rgba(126,255,247,0.5)'), ('LETS_PLAY_ALCOHOL_GAME', '🎮술게임해요/rgba(220,121,255,0.5)'), ('LETS_TALK', '💬차분히 대화해요/rgba(255,222,222,0.8)'), ('WE_EAT_ANYTHING', '🤔아무거나 먹어요/rgba(250,187,112,0.5)'), ('WE_EAT_CHICKEN', '🍗치킨 먹어요/rgba(255,217,159,0.8)'), ('LETS_PLAY_HOT', '🔥화끈하게 놀아요/rgba(255,109,109,0.5)'), ('PLAY_UNTIL_END', '💪끝까지 달려요/rgba(147,101,244,0.5)'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻1차로만 가볍게 놀아요/rgba(226,255,45,0.5)'), ('DRINK_MAKGULI', '☂️비 오는 날은 막걸리/rgba(115,221,255,0.5)')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
    ]
