# Generated by Django 3.2.13 on 2023-05-07 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_auto_20230508_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent24HrTopGroupAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(default=dict)),
                ('aggregated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='ReportedGroup',
            new_name='ReportedGroupV2',
        ),
        migrations.AlterField(
            model_name='reportedgroupv2',
            name='reported_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='group.groupv2'),
        ),
    ]
