# Generated by Django 3.2.13 on 2023-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20230824_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofilephotopurchased',
            name='method',
            field=models.IntegerField(choices=[(0, 'Point'), (1, 'Advertisement')], default=0),
        ),
        migrations.AddField(
            model_name='historicalgroupprofilephotopurchased',
            name='method',
            field=models.IntegerField(choices=[(0, 'Point'), (1, 'Advertisement')], default=0),
        ),
    ]
