# Generated by Django 3.2.13 on 2023-05-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20230508_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='meetup_address',
            field=models.CharField(default='서욽특별시 압강남구 압구정로 133', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='meetup_address',
            field=models.CharField(default='서울특별시 강남구 압구정로 133', max_length=250),
            preserve_default=False,
        ),
    ]
