# Generated by Django 3.2.13 on 2023-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20230508_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='match_point',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='match_point',
            field=models.IntegerField(default=1),
        ),
    ]
