# Generated by Django 3.2.13 on 2023-10-16 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20231005_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
