# Generated by Django 3.2.13 on 2023-11-13 11:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20231016_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘 애교가 많아요/rgba(217,225,239,1.0)'), ('A_LOT_OF_PLAYFULNESS', '😝 장난기 많아요/rgba(217,225,239,1.0)'), ('INTERNATIONAL', '🌏 다국적이에요/rgba(217,225,239,1.0)'), ('A_LOT_OF_ACTIVENESS', '😃 활달해요/rgba(217,225,239,1.0)'), ('TENDS_TO_BE_QUIET', '😷 조용한 편이에요/rgba(217,225,239,1.0)'), ('A_LOT_OF_SHYNESS', '🙈 수줍음 많아요/rgba(217,225,239,1.0)'), ('NICE_BODY_SHAPE', '👍 몸매가 좋아요/rgba(217,225,239,1.0)'), ('WE_ARE_HANDSOME', '🤩 잘생겼어요/rgba(217,225,239,1.0)'), ('WE_ARE_PRETTY', '😍 예뻐요/rgba(217,225,239,1.0)'), ('WE_ARE_GOOD_LOOKING', '☺️ 훈훈해요/rgba(217,225,239,1.0)'), ('FASHION_PEOPLE', '🕶 패셔니스타/rgba(217,225,239,1.0)'), ('WE_ARE_KING', '👑 우리가 왕이야/rgba(217,225,239,1.0)'), ('WE_LIKE_SPORTS', '💪 운동을 좋아해요/rgba(217,225,239,1.0)'), ('A_LOT_OF_LAUGHING', '🤣 웃음이 많아요/rgba(217,225,239,1.0)'), ('GOOD_AT_TALKING', '💬 대화를 잘해요/rgba(217,225,239,1.0)'), ('WE_ARE_HUMOROUS', '😂 유머러스해요/rgba(217,225,239,1.0)')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='groupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷 와인 좋아해요/rgba(217,225,239,1.0)'), ('WE_LIKE_BEER', '🍺 맥주 좋아해요/rgba(217,225,239,1.0)'), ('WE_LIKE_MEAT', '🍖 고기 먹어요/rgba(217,225,239,1.0)'), ('WE_LIKE_SOJU', '💚 소주 좋아해요/rgba(217,225,239,1.0)'), ('WE_LIKE_SOUP', '🍲 국물안주 고고/rgba(217,225,239,1.0)'), ('LETS_PLAY_ALCOHOL_GAME', '🎮 술게임해요/rgba(217,225,239,1.0)'), ('LETS_TALK', '💬 차분히 대화/rgba(217,225,239,1.0)'), ('WE_EAT_ANYTHING', '🤔 암거나 먹어요/rgba(217,225,239,1.0)'), ('WE_EAT_CHICKEN', '🍗 치킨 먹어요/rgba(217,225,239,1.0)'), ('LETS_PLAY_HOT', '🔥 화끈하게 놀자/rgba(217,225,239,1.0)'), ('PLAY_UNTIL_END', '💪 끝까지 달려요/rgba(217,225,239,1.0)'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻가볍게 1차만/rgba(217,225,239,1.0)'), ('DRINK_MAKGULI', '☂️ 비올땐 막걸리/rgba(217,225,239,1.0)')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='about_our_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('A_LOT_OF_CUTENESS', '😘 애교가 많아요/rgba(217,225,239,1.0)'), ('A_LOT_OF_PLAYFULNESS', '😝 장난기 많아요/rgba(217,225,239,1.0)'), ('INTERNATIONAL', '🌏 다국적이에요/rgba(217,225,239,1.0)'), ('A_LOT_OF_ACTIVENESS', '😃 활달해요/rgba(217,225,239,1.0)'), ('TENDS_TO_BE_QUIET', '😷 조용한 편이에요/rgba(217,225,239,1.0)'), ('A_LOT_OF_SHYNESS', '🙈 수줍음 많아요/rgba(217,225,239,1.0)'), ('NICE_BODY_SHAPE', '👍 몸매가 좋아요/rgba(217,225,239,1.0)'), ('WE_ARE_HANDSOME', '🤩 잘생겼어요/rgba(217,225,239,1.0)'), ('WE_ARE_PRETTY', '😍 예뻐요/rgba(217,225,239,1.0)'), ('WE_ARE_GOOD_LOOKING', '☺️ 훈훈해요/rgba(217,225,239,1.0)'), ('FASHION_PEOPLE', '🕶 패셔니스타/rgba(217,225,239,1.0)'), ('WE_ARE_KING', '👑 우리가 왕이야/rgba(217,225,239,1.0)'), ('WE_LIKE_SPORTS', '💪 운동을 좋아해요/rgba(217,225,239,1.0)'), ('A_LOT_OF_LAUGHING', '🤣 웃음이 많아요/rgba(217,225,239,1.0)'), ('GOOD_AT_TALKING', '💬 대화를 잘해요/rgba(217,225,239,1.0)'), ('WE_ARE_HUMOROUS', '😂 유머러스해요/rgba(217,225,239,1.0)')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalgroupv2',
            name='meeting_we_want_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('WE_LIKE_WINE', '🍷 와인 좋아해요/rgba(217,225,239,1.0)'), ('WE_LIKE_BEER', '🍺 맥주 좋아해요/rgba(217,225,239,1.0)'), ('WE_LIKE_MEAT', '🍖 고기 먹어요/rgba(217,225,239,1.0)'), ('WE_LIKE_SOJU', '💚 소주 좋아해요/rgba(217,225,239,1.0)'), ('WE_LIKE_SOUP', '🍲 국물안주 고고/rgba(217,225,239,1.0)'), ('LETS_PLAY_ALCOHOL_GAME', '🎮 술게임해요/rgba(217,225,239,1.0)'), ('LETS_TALK', '💬 차분히 대화/rgba(217,225,239,1.0)'), ('WE_EAT_ANYTHING', '🤔 암거나 먹어요/rgba(217,225,239,1.0)'), ('WE_EAT_CHICKEN', '🍗 치킨 먹어요/rgba(217,225,239,1.0)'), ('LETS_PLAY_HOT', '🔥 화끈하게 놀자/rgba(217,225,239,1.0)'), ('PLAY_UNTIL_END', '💪 끝까지 달려요/rgba(217,225,239,1.0)'), ('PLAY_SIMPLE_UNTIL_FIRST', '🍻가볍게 1차만/rgba(217,225,239,1.0)'), ('DRINK_MAKGULI', '☂️ 비올땐 막걸리/rgba(217,225,239,1.0)')], max_length=128, null=True), blank=True, null=True, size=None),
        ),
    ]
