# Generated by Django 3.2.13 on 2023-11-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_auto_20231113_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupv2',
            name='notified_to_update_meetup_date_after_one_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupv2',
            name='notified_to_update_meetup_date_after_one_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupv2',
            name='notified_to_update_meetup_date_after_three_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupv2',
            name='notified_to_update_meetup_date_after_two_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='notified_to_update_meetup_date_after_one_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='notified_to_update_meetup_date_after_one_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='notified_to_update_meetup_date_after_three_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgroupv2',
            name='notified_to_update_meetup_date_after_two_week',
            field=models.BooleanField(default=False),
        ),
    ]
