# Generated by Django 3.2.13 on 2022-12-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_streamchannel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamchannel',
            old_name='joined_groups',
            new_name='participants',
        ),
    ]
