# Generated by Django 3.2.13 on 2022-04-29 07:09

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotplace',
            old_name='zone_boundary_info',
            new_name='zone_boundary_geoinfos',
        ),
        migrations.AddField(
            model_name='hotplace',
            name='zone_center_geoinfo',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
            preserve_default=False,
        ),
    ]
