# Generated by Django 3.2.13 on 2022-04-29 07:10

import django.contrib.postgres.fields
from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20220429_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplace',
            name='zone_boundary_geoinfos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_google_maps.fields.GeoLocationField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='zone_center_geoinfo',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
