# Generated by Django 3.2.13 on 2022-12-03 16:56

import django.contrib.postgres.fields
from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplace',
            name='zone_boundary_geoinfos_for_fake_chat',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_google_maps.fields.GeoLocationField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
