# Generated by Django 3.2.13 on 2022-12-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0002_hotplace_zone_boundary_geoinfos_for_fake_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplace',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
