# Generated by Django 3.2.13 on 2022-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_url', models.URLField()),
                ('terms_of_service_url', models.URLField()),
                ('privacy_policy_url', models.URLField()),
                ('terms_of_location_service_url', models.URLField()),
                ('business_registration_url', models.URLField()),
            ],
        ),
    ]
