# Generated by Django 3.2.13 on 2023-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_first_signup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_first_signup',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='has_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_main_profile_photo_under_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_main_profile_photo_under_verification',
            field=models.BooleanField(default=False),
        ),
    ]
