# Generated by Django 3.2.13 on 2022-10-15 08:29

from django.db import migrations, models
import heymatch.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='free_pass',
            field=models.IntegerField(blank=True, choices=[(0, 'one-day-pass')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='free_pass_active_until',
            field=models.DateTimeField(blank=True, default=heymatch.apps.user.models.free_pass_default_time, null=True),
        ),
    ]
