# Generated by Django 3.2.13 on 2023-05-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230519_1731'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofileimage',
            managers=[
            ],
        ),
    ]
