# Generated by Django 3.2.13 on 2022-10-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221015_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balance',
            new_name='point_balance',
        ),
    ]
