# Generated by Django 3.2.13 on 2023-08-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230809_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='has_finished_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_finished_guide',
            field=models.BooleanField(default=False),
        ),
    ]
