# Generated by Django 3.2.13 on 2022-11-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_deletescheduleduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletescheduleduser',
            name='delete_reason',
            field=models.TextField(default='', max_length=500),
        ),
    ]
