# Generated by Django 3.2.13 on 2022-10-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_balance_user_point_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='free_pass',
        ),
    ]
