# Generated by Django 3.2.13 on 2022-11-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_deletescheduleduser_delete_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletescheduleduser',
            name='delete_reason',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
