# Generated by Django 3.2.13 on 2022-10-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_balance_user_point_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='free_pass',
            field=models.BooleanField(default=False),
        ),
    ]
