# Generated by Django 3.2.13 on 2023-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230822_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='num_of_available_ads',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='num_of_available_ads',
            field=models.IntegerField(default=5),
        ),
    ]
