# Generated by Django 3.2.13 on 2023-10-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230909_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='num_of_available_ads',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='point_balance',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_of_available_ads',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='point_balance',
            field=models.IntegerField(default=15),
        ),
    ]
