# Generated by Django 3.2.13 on 2023-05-24 17:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230520_0223'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofileimage',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
