# Generated by Django 3.2.13 on 2022-10-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_free_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_pass',
            field=models.BooleanField(default=False),
        ),
    ]
