# Generated by Django 3.2.13 on 2022-11-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_deletescheduleduser_delete_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='point_balance',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='point_balance',
            field=models.IntegerField(default=10),
        ),
    ]
