# Generated by Django 3.2.13 on 2023-06-05 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofileimage_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnBoarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('onboarding_basic_info_incomplete', 'Basic Info Incomplete'), ('onboarding_profile_under_verification_extra_info_incomplete', 'Profile Under Verification Extra Info Incomplete'), ('onboarding_profile_under_verification_extra_info_completed', 'Profile Under Verification Extra Info Complete'), ('onboarding_profile_rejected', 'Profile Rejected'), ('onboarding_completed', 'Onboarding Completed')], default='onboarding_basic_info_incomplete', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
