# Generated by Django 3.2.13 on 2022-11-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_free_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stream_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
