# Generated by Django 3.2.13 on 2022-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20221123_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletescheduleduser',
            name='delete_processed',
        ),
        migrations.AddField(
            model_name='deletescheduleduser',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='WAITING', max_length=24),
        ),
    ]
