# Generated by Django 3.2.13 on 2023-11-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20231005_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='notified_to_make_first_group_after_join_10min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='notified_to_make_first_group_after_join_1day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='notified_to_make_first_group_after_join_1hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notified_to_make_first_group_after_join_10min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notified_to_make_first_group_after_join_1day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notified_to_make_first_group_after_join_1hr',
            field=models.BooleanField(default=False),
        ),
    ]
