# Generated by Django 3.2.13 on 2023-06-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_useronboarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronboarding',
            name='status',
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='basic_info_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='extra_info_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='profile_photo_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='profile_photo_under_verification',
            field=models.BooleanField(default=False),
        ),
    ]
