# Generated by Django 3.2.13 on 2022-12-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20221202_2306'),
        ('user', '0006_auto_20221123_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletescheduleduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='group.group'),
        ),
    ]
