# Generated by Django 3.2.13 on 2023-06-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230606_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='has_account',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_main_profile_photo_under_verification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_main_profile_photo_under_verification',
        ),
    ]
