# Generated by Django 3.2.13 on 2022-12-03 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0001_initial'),
        ('user', '0007_auto_20221202_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hotplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fake_chat_user_hotplace', to='hotplace.hotplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fake_chat_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
