# Generated by Django 3.2.13 on 2022-12-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_fakechatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_old_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_old_user',
            field=models.BooleanField(default=True),
        ),
    ]
