# Generated by Django 3.2.13 on 2023-06-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230606_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronboarding',
            name='extra_info_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
