# Generated by Django 3.2.13 on 2022-12-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20221205_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='is_old_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_old_user',
            field=models.BooleanField(default=False),
        ),
    ]
