# Generated by Django 3.2.13 on 2023-06-14 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_useronboarding_extra_info_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofileimage',
            name='expected_verification_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 8, 19, 30, 537800, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='expected_verification_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 8, 19, 30, 537800, tzinfo=utc)),
        ),
    ]
