# Generated by Django 3.2.13 on 2023-06-14 08:27

from django.db import migrations, models
import heymatch.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230614_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofileimage',
            name='expected_verification_datetime',
            field=models.DateTimeField(default=heymatch.apps.user.models.auto_expected_verification_datetime),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='expected_verification_datetime',
            field=models.DateTimeField(default=heymatch.apps.user.models.auto_expected_verification_datetime),
        ),
    ]
