# Generated by Django 3.2.13 on 2023-03-01 05:16

import birthday.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import heymatch.apps.user.models
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20221209_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='is_old_user',
            new_name='agreed_to_terms',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_old_user',
            new_name='agreed_to_terms',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='birthdate',
            field=birthday.fields.BirthdayField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='birthdate_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=birthday.fields.BirthdayField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.ImageField(upload_to=heymatch.apps.user.models.upload_to)),
                ('image_blurred', models.ImageField(upload_to=heymatch.apps.user.models.upload_to)),
                ('thumbnail', models.ImageField(upload_to=heymatch.apps.user.models.upload_to)),
                ('thumbnail_blurred', models.ImageField(upload_to=heymatch.apps.user.models.upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserProfileImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.TextField(max_length=100)),
                ('image_blurred', models.TextField(max_length=100)),
                ('thumbnail', models.TextField(max_length=100)),
                ('thumbnail_blurred', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user profile image',
                'verbose_name_plural': 'historical user profile images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
