# Generated by Django 3.2.13 on 2023-06-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20230614_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronboarding',
            name='profile_photo_rejected_reason',
            field=models.CharField(blank=True, choices=[('no_face_found', 'No Face Found'), ('more_than_one_face', 'More Than One Face'), ('unknown', 'Unknown')], default=None, max_length=25, null=True),
        ),
    ]
