# Generated by Django 3.2.13 on 2023-06-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_useronboarding_profile_photo_rejected_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='invitation_code',
            field=models.CharField(db_index=True, default='AAAA', editable=False, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_code',
            field=models.CharField(default='AAAA', editable=False, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
