# Generated by Django 3.2.13 on 2023-03-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20230303_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='final_education',
            field=models.CharField(blank=True, choices=[('high_school', '고등학교'), ('bachelor', '학사'), ('master_or_above', '석박사'), ('medical_graduate', '의/약/치전원'), ('law_school', '로스쿨'), ('etc', '기타')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_company_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_school_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='job_title',
            field=models.CharField(blank=True, choices=[('college_student', '대학생'), ('employee', '직장인'), ('self_employed', '자영업'), ('part_time', '파트타임'), ('businessman', '사업가'), ('etc', '기타')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='school_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='final_education',
            field=models.CharField(blank=True, choices=[('high_school', '고등학교'), ('bachelor', '학사'), ('master_or_above', '석박사'), ('medical_graduate', '의/약/치전원'), ('law_school', '로스쿨'), ('etc', '기타')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_school_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('college_student', '대학생'), ('employee', '직장인'), ('self_employed', '자영업'), ('part_time', '파트타임'), ('businessman', '사업가'), ('etc', '기타')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
