# Generated by Django 3.2.13 on 2023-06-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20230618_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_invitation_received_user', to=settings.AUTH_USER_MODEL)),
                ('sent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_invitation_sent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
