# Generated by Django 3.2.13 on 2023-03-04 17:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20230305_0235'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofileimage',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
