# Generated by Django 3.2.13 on 2023-06-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='block_my_school_or_company_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='block_my_school_or_company_users',
            field=models.BooleanField(default=False),
        ),
    ]
