# Generated by Django 3.2.13 on 2023-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20230619_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='job_title',
            field=models.CharField(blank=True, choices=[('college_student', 'College Student'), ('employee', 'Employee'), ('practitioner', 'Practitioner'), ('self_employed', 'Self Employed'), ('part_time', 'Part Time'), ('businessman', 'Businessman'), ('etc', 'Etc')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('college_student', 'College Student'), ('employee', 'Employee'), ('practitioner', 'Practitioner'), ('self_employed', 'Self Employed'), ('part_time', 'Part Time'), ('businessman', 'Businessman'), ('etc', 'Etc')], default=None, max_length=32, null=True),
        ),
    ]
