# Generated by Django 3.2.13 on 2023-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userprofileimage_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofileimage',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofileimage',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='historicaluserprofileimage',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Not verified'), ('u', 'Under verification'), ('a', 'Accepted'), ('r', 'Rejected')], default='n', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Not verified'), ('u', 'Under verification'), ('a', 'Accepted'), ('r', 'Rejected')], default='n', max_length=1, null=True),
        ),
    ]
