# Generated by Django 3.2.13 on 2023-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20230305_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofileimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
