# Generated by Django 3.2.13 on 2023-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20230622_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronboarding',
            name='profile_photo_rejected_reason',
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
    ]
