# Generated by Django 3.2.13 on 2023-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20230305_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
