# Generated by Django 3.2.13 on 2023-07-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_useronboarding_profile_photo_rejected_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronboarding',
            name='basic_info_completed',
        ),
        migrations.RemoveField(
            model_name='useronboarding',
            name='extra_info_completed',
        ),
        migrations.RemoveField(
            model_name='useronboarding',
            name='extra_info_in_progress',
        ),
    ]
