# Generated by Django 3.2.13 on 2023-03-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20230308_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='body_form',
            new_name='male_body_form',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='body_form',
            new_name='male_body_form',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='female_body_form',
            field=models.CharField(blank=True, choices=[('thin', '마른'), ('slender', '슬림탄탄'), ('normal', '보통'), ('chubby', '통통한'), ('glamourous', '글래머러스한'), ('bulky', '덩치가있는')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='female_body_form',
            field=models.CharField(blank=True, choices=[('thin', '마른'), ('slender', '슬림탄탄'), ('normal', '보통'), ('chubby', '통통한'), ('glamourous', '글래머러스한'), ('bulky', '덩치가있는')], max_length=15, null=True),
        ),
    ]
