# Generated by Django 3.2.13 on 2023-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20230308_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='company_name',
            new_name='verified_company_name',
        ),
        migrations.RenameField(
            model_name='historicaluser',
            old_name='school_name',
            new_name='verified_school_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company_name',
            new_name='verified_company_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='school_name',
            new_name='verified_school_name',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='final_education',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_company_verified',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_school_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='final_education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_company_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_school_verified',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='job_title',
            field=models.CharField(blank=True, choices=[('college_student', '대학(원)생'), ('employee', '직장인'), ('self_employed', '자영업'), ('part_time', '파트타임'), ('businessman', '사업가'), ('etc', '기타')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('college_student', '대학(원)생'), ('employee', '직장인'), ('self_employed', '자영업'), ('part_time', '파트타임'), ('businessman', '사업가'), ('etc', '기타')], default=None, max_length=32, null=True),
        ),
    ]
