# Generated by Django 3.2.13 on 2023-03-12 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import heymatch.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20230310_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('school', 'School'), ('company', 'Company')], max_length=15)),
                ('code', models.CharField(default=heymatch.apps.user.models.auto_generate_email_verification_code, max_length=5)),
                ('active_until', models.DateTimeField(default=heymatch.apps.user.models.email_verification_code_valid_until)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_email_verification_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
