# Generated by Django 3.2.13 on 2023-03-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='female_body_form',
            field=models.CharField(blank=True, choices=[('thin', 'Thin'), ('slender', 'Slender'), ('normal', 'Normal'), ('chubby', 'Chubby'), ('glamorous', 'Glamorous'), ('bulky', 'Bulky')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='job_title',
            field=models.CharField(blank=True, choices=[('college_student', 'College Student'), ('employee', 'Employee'), ('self_employed', 'Self Employed'), ('part_time', 'Part Time'), ('businessman', 'Businessman'), ('etc', 'Etc')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='male_body_form',
            field=models.CharField(blank=True, choices=[('thin', 'Thin'), ('slender', 'Slender'), ('normal', 'Normal'), ('chubby', 'Chubby'), ('muscular', 'Muscular'), ('bulky', 'Bulky')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='female_body_form',
            field=models.CharField(blank=True, choices=[('thin', 'Thin'), ('slender', 'Slender'), ('normal', 'Normal'), ('chubby', 'Chubby'), ('glamorous', 'Glamorous'), ('bulky', 'Bulky')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('college_student', 'College Student'), ('employee', 'Employee'), ('self_employed', 'Self Employed'), ('part_time', 'Part Time'), ('businessman', 'Businessman'), ('etc', 'Etc')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='male_body_form',
            field=models.CharField(blank=True, choices=[('thin', 'Thin'), ('slender', 'Slender'), ('normal', 'Normal'), ('chubby', 'Chubby'), ('muscular', 'Muscular'), ('bulky', 'Bulky')], max_length=15, null=True),
        ),
    ]
