# Generated by Django 3.2.13 on 2023-03-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20230314_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofileimage',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Not Verified'), ('u', 'Under Verification'), ('a', 'Accepted'), ('r', 'Rejected')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Not Verified'), ('u', 'Under Verification'), ('a', 'Accepted'), ('r', 'Rejected')], default='n', max_length=1, null=True),
        ),
    ]
